OCAMLBUILD = ocamlbuild
LIBSB = unix,str,dynlink,nums
PROPERERRS = -warn-error,+4+8+9+11+12+25+28
FLAGS = $(PROPERERRS),-annot,-ccopt,-fopenmp 
OBB_FLAGS = -I $(LIBSB) -cflags $(FLAGS) -lflags $(FLAGS) -lexflag -q -yaccflag -v  
all:
	ocamlc -annot -c globals.ml 
	ocamlc -annot -c error.ml 
	ocamlc -annot -c gen.ml 
	ocamlc -annot -c debug.ml 
	ocamlc -annot -c scriptarguments.ml 
	ocamlc  -annot -I dynlink.cma nums.cma str.cma unix.cma globals.cmo error.cmo gen.cmo debug.cmo scriptarguments.cmo tut9.ml -o tut9.exe
clean:
	rm *.cmo *.cmi *.annot tut9.exe

